version: '3.8'
services:
  api:
    container_name: "nest_api_dev"
    # image: "nest_api_${NODE_ENV}"
    build:
      context: ./
      target: "builder"
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - NODE_ENV:${NODE_ENV}
      - DATABASE_HOST=db
    entrypoint: ["npm", "run", "start:dev"]
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - nestjs-network
    volumes:
      - ./:/app
    restart: unless-stopped
    depends_on:
      - db
  db:
    container_name: "memory_partner_db"
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "nest_react_login_db"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - 3306:3306
    networks:
      - nestjs-network
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
networks:
  nestjs-network:
