version: '3.8'
services:
  api:
    container_name: "nest_api_${NODE_ENV}"
    image: "nest_api_${NODE_ENV}"
    environment:
      - NODE_ENV:${NODE_ENV}
    build:
      context: ./
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start:${NODE_ENV}"]
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - nestjs-network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DB}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - 3306:3306
    networks:
      - nestjs-network
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
networks:
  nestjs-network: